pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Aicodemax"
include(
    ":app",
    ":core:common",
    ":core:state",
    ":core:resources",
    ":ai:core",
    ":ai:tasks",
    ":ai:agents",
    ":ai:models",
    ":tools:registry",
    ":tools:gateway",
    ":tools:files",
    ":tools:editor",
    ":tools:terminal",
    ":tools:terminal_runtime",
    ":tools:builder",
    ":tools:git",
    ":tools:git_runtime",
    ":tools:capability",
    ":tools:runtime",
    ":tools:project",
    ":tools:tester",
    ":tools:debug",
    ":tools:debug_runtime",
    ":tools:memory_runtime",
    ":tools:skill_runtime",
    ":tools:voice",
    ":tools:voice_runtime",
    ":tools:image",
    ":tools:image_runtime",
    ":tools:github",
    ":tools:browser",
    ":tools:browser_runtime",
    ":data:checkpoint",
    ":data:audit",
    ":data:memory",
    ":data:skills",
    ":data:conversations",
    ":data:settings",
    ":data:backup",
    ":ui:designsystem",
    ":ui:chat",
    ":ui:workspace",
    ":ui:settings",
)
