package com.aicodemax.tools.capability

import com.aicodemax.tools.registry.CapabilityLayer
import com.aicodemax.tools.registry.CapabilityStatus
import com.aicodemax.tools.registry.InMemoryToolRegistry
import com.aicodemax.tools.registry.LayerCapability
import com.aicodemax.tools.registry.ToolDescriptor
import com.aicodemax.tools.registry.ToolRegistry

/**
 * The capability catalog the app actually ships today.
 * Native engines first; the terminal CLI adapter exists ONLY as fallback (CP-32).
 */
object StandardCapabilities {
    fun bindings(): List<CapabilityBinding> = listOf(
        // File engine (native).
        CapabilityBinding("files.read", "files", "read", AdapterKind.NATIVE,
            metadata = meta("files", "อ่านไฟล์ใน workspace", listOf("path"), listOf("content"), emptyList(), false, "canonical-path containment", "re-read")),
        CapabilityBinding("files.list", "files", "list", AdapterKind.NATIVE,
            metadata = meta("files", "list ไฟล์ในโฟลเดอร์", listOf("path?"), listOf("entries"), emptyList(), false, "canonical-path containment", "re-list")),
        CapabilityBinding("files.mkdir", "files", "mkdir", AdapterKind.NATIVE,
            metadata = meta("files", "สร้างโฟลเดอร์", listOf("path"), listOf("ok"), listOf("fs.write"), false, "list shows dir", "retry")),
        CapabilityBinding("files.delete", "files", "delete", AdapterKind.NATIVE,
            metadata = meta("files", "ลบไฟล์/โฟลเดอร์", listOf("path"), listOf("ok"), listOf("fs.delete"), false, "path gone", "checkpoint restore")),
        CapabilityBinding("files.copy", "files", "copy", AdapterKind.NATIVE,
            metadata = meta("files", "คัดลอกไฟล์", listOf("from,to"), listOf("ok"), listOf("fs.write"), false, "target readable", "retry")),
        CapabilityBinding("files.move", "files", "move", AdapterKind.NATIVE,
            metadata = meta("files", "ย้ายไฟล์", listOf("from,to"), listOf("ok"), listOf("fs.write"), false, "target readable + source gone", "retry")),
        CapabilityBinding("files.search", "files", "search", AdapterKind.NATIVE,
            metadata = meta("files", "ค้นหาข้อความในไฟล์", listOf("query,path?"), listOf("matches"), emptyList(), false, "bounded result set", "narrow query")),
        CapabilityBinding("files.archive", "files", "archive", AdapterKind.NATIVE,
            metadata = meta("files", "บีบอัดเป็น zip", listOf("paths,out"), listOf("archive"), listOf("fs.write"), false, "zip-slip guarded write", "retry")),
        CapabilityBinding("files.unarchive", "files", "unarchive", AdapterKind.NATIVE,
            metadata = meta("files", "แตกไฟล์ zip", listOf("archive,out?"), listOf("files"), listOf("fs.write"), false, "zip-slip guarded extract", "retry")),
        CapabilityBinding("files.metadata", "files", "metadata", AdapterKind.NATIVE,
            metadata = meta("files", "ข้อมูลไฟล์", listOf("path"), listOf("size,modified"), emptyList(), false, "stat", "re-stat")),
        // Code engine (native).
        CapabilityBinding("editor.set", "editor", "set", AdapterKind.NATIVE,
            metadata = meta("editor", "เปิด/ตั้งค่าบัฟเฟอร์แก้ไข", listOf("path"), listOf("buffer"), emptyList(), false, "file exists", "re-open")),
        CapabilityBinding("editor.save", "editor", "save", AdapterKind.NATIVE,
            metadata = meta("editor", "บันทึกบัฟเฟอร์ลงไฟล์", listOf("path,content"), listOf("ok"), listOf("fs.write"), false, "read-back bytes", "re-save")),
        CapabilityBinding("editor.preview", "editor", "preview", AdapterKind.NATIVE,
            metadata = meta("editor", "ดู diff ก่อนแก้", listOf("path,startLine,endLine,replacement"), listOf("diff"), emptyList(), false, "pure (no write)", "adjust range")),
        CapabilityBinding("editor.patch", "editor", "patch", AdapterKind.NATIVE,
            metadata = meta("editor", "แก้ไฟล์แบบ patch", listOf("path,patch"), listOf("ok"), listOf("fs.write"), false, "read-back bytes", "inverse patch")),
        // Git engine (native, JGit).
        CapabilityBinding("git.ensure", "git", "ensure", AdapterKind.NATIVE,
            metadata = meta("git", "init/open repo ถ้าจำเป็น", listOf("repo"), listOf("ok"), listOf("fs.write"), false, ".git present", "retry")),
        CapabilityBinding("git.status", "git", "status", AdapterKind.NATIVE,
            metadata = meta("git", "สถานะ working tree", listOf("repo"), listOf("status"), emptyList(), false, "JGit status", "re-status")),
        CapabilityBinding("git.log", "git", "log", AdapterKind.NATIVE,
            metadata = meta("git", "ประวัติ commit", listOf("repo,limit?"), listOf("commits"), emptyList(), false, "log parse", "re-log")),
        CapabilityBinding("git.stage", "git", "stage", AdapterKind.NATIVE,
            metadata = meta("git", "stage ไฟล์", listOf("repo,paths?"), listOf("ok"), listOf("fs.write"), false, "status shows staged", "retry")),
        CapabilityBinding("git.commit", "git", "commit", AdapterKind.NATIVE,
            metadata = meta("git", "commit การเปลี่ยน", listOf("repo,message"), listOf("sha"), listOf("fs.write"), false, "log shows commit", "amend/retry")),
        CapabilityBinding("git.branch", "git", "branch", AdapterKind.NATIVE,
            metadata = meta("git", "list/สร้าง branch", listOf("repo,name?"), listOf("branches"), listOf("fs.write"), false, "branch list", "retry")),
        CapabilityBinding("git.checkout", "git", "checkout", AdapterKind.NATIVE,
            metadata = meta("git", "สลับ branch", listOf("repo,name"), listOf("ok"), listOf("fs.write"), false, "HEAD moved", "checkout back")),
        CapabilityBinding("git.diff", "git", "diff", AdapterKind.NATIVE,
            metadata = meta("git", "ดู diff", listOf("repo"), listOf("diff"), emptyList(), false, "JGit diff", "re-diff")),
        CapabilityBinding("git.stash", "git", "stash", AdapterKind.NATIVE,
            metadata = meta("git", "เก็บงานชั่วคราว", listOf("repo"), listOf("ok"), listOf("fs.write"), false, "stash list", "stash-pop")),
        CapabilityBinding("git.stash-pop", "git", "stash-pop", AdapterKind.NATIVE,
            metadata = meta("git", "คืน stash", listOf("repo"), listOf("ok"), listOf("fs.write"), false, "tree matches", "re-stash")),
        CapabilityBinding("git.merge", "git", "merge", AdapterKind.NATIVE,
            metadata = meta("git", "merge branch", listOf("repo,name"), listOf("ok|conflicts"), listOf("fs.write"), false, "conflict report", "abort + resolve")),
        CapabilityBinding("git.conflicts", "git", "conflicts", AdapterKind.NATIVE,
            metadata = meta("git", "list ไฟล์ชนกัน", listOf("repo"), listOf("paths"), emptyList(), false, "status scan", "re-scan")),
        CapabilityBinding("git.push", "git", "push", AdapterKind.NATIVE,
            metadata = meta("git", "push ขึ้น remote", listOf("repo,remote?,branch?"), listOf("ok"), listOf("fs.write","network"), true, "remote refs", "pull then push")),
        CapabilityBinding("git.pull", "git", "pull", AdapterKind.NATIVE,
            metadata = meta("git", "pull จาก remote", listOf("repo,remote?,branch?"), listOf("ok"), listOf("fs.write","network"), true, "log advanced", "resolve conflicts")),
        CapabilityBinding("git.clone", "git", "clone", AdapterKind.NATIVE,
            metadata = meta("git", "clone repo", listOf("url,dest"), listOf("ok"), listOf("fs.write","network"), true, "dir is repo", "re-clone")),
        // Browser engine (native, WebView).
        CapabilityBinding("browser.open", "browser", "open", AdapterKind.NATIVE,
            metadata = meta("browser", "เปิดแท็บใหม่", listOf("url"), listOf("tabId"), listOf("network"), true, "tab listed", "re-open")),
        CapabilityBinding("browser.close", "browser", "close", AdapterKind.NATIVE,
            metadata = meta("browser", "ปิดแท็บ", listOf("tabId"), listOf("ok"), emptyList(), false, "tab gone", "re-list")),
        CapabilityBinding("browser.list", "browser", "list", AdapterKind.NATIVE,
            metadata = meta("browser", "list แท็บ", emptyList(), listOf("tabs"), emptyList(), false, "tab count", "re-list")),
        CapabilityBinding("browser.navigate", "browser", "navigate", AdapterKind.NATIVE,
            metadata = meta("browser", "เปลี่ยน URL ในแท็บ", listOf("tabId,url"), listOf("ok"), listOf("network"), true, "tab url", "go back")),
        // Debug engine (native).
        CapabilityBinding("debug.analyze", "debug", "analyze", AdapterKind.NATIVE,
            metadata = meta("debug", "วิเคราะห์ stack trace หาสาเหตุ", listOf("error"), listOf("finding"), emptyList(), false, "parse confidence", "ask for full trace")),
        // Memory engine (native).
        CapabilityBinding("memory.save", "memory", "save", AdapterKind.NATIVE,
            metadata = meta("memory", "จำ key=value ระดับ global", listOf("key,value"), listOf("ok"), emptyList(), false, "read-back", "retry")),
        CapabilityBinding("memory.recall", "memory", "recall", AdapterKind.NATIVE,
            metadata = meta("memory", "ทวนความจำ global", listOf("key"), listOf("value"), emptyList(), false, "record found", "ask user")),
        // Skill engine (native).
        CapabilityBinding("skill.list", "skill", "list", AdapterKind.NATIVE,
            metadata = meta("skill", "list สกิลทั้งหมด", emptyList(), listOf("skills"), emptyList(), false, "index read", "re-list")),
        CapabilityBinding("skill.get", "skill", "get", AdapterKind.NATIVE,
            metadata = meta("skill", "อ่านเนื้อหาสกิล", listOf("id"), listOf("content"), emptyList(), false, "file read", "re-get")),
        CapabilityBinding("skill.install", "skill", "install", AdapterKind.NATIVE,
            metadata = meta("skill", "ติดตั้งสกิลจากไฟล์ workspace", listOf("path"), listOf("id"), listOf("fs.write"), false, "id listed", "fix file")),
        CapabilityBinding("skill.inject", "skill", "inject", AdapterKind.NATIVE,
            metadata = meta("skill", "ฉีดสกิลเข้า context", listOf("ids"), listOf("context"), emptyList(), false, "ids found", "list first")),
        CapabilityBinding("skill.remove", "skill", "remove", AdapterKind.NATIVE,
            metadata = meta("skill", "ลบสกิลที่ติดตั้ง", listOf("id"), listOf("ok"), listOf("fs.delete"), false, "id gone", "re-remove")),
        // Voice engine (native, Android speech APIs).
        CapabilityBinding("voice.listen", "voice", "listen", AdapterKind.NATIVE,
            metadata = meta("voice", "ฟังเสียงแล้วถอดเป็นข้อความ", listOf("lang?,timeoutMs?"), listOf("transcript"), listOf("mic"), false, "text heard", "re-listen")),
        CapabilityBinding("voice.speak", "voice", "speak", AdapterKind.NATIVE,
            metadata = meta("voice", "พูดข้อความออกเสียง", listOf("text,lang?"), listOf("ok"), listOf("audio"), false, "utterance done", "retry")),
        CapabilityBinding("voice.stop", "voice", "stop", AdapterKind.NATIVE,
            metadata = meta("voice", "หยุดเสียงที่กำลังพูด", emptyList(), listOf("ok"), emptyList(), false, "silent", "re-stop")),
        CapabilityBinding("voice.status", "voice", "status", AdapterKind.NATIVE,
            metadata = meta("voice", "เช็คความพร้อม STT/TTS", emptyList(), listOf("status"), emptyList(), false, "engine probe", "re-check")),
        // Image engine (native, header probe + pixel ops).
        CapabilityBinding("image.info", "image", "info", AdapterKind.NATIVE,
            metadata = meta("image", "ดูฟอร์แมต+ขนาดรูป", listOf("path"), listOf("info"), emptyList(), false, "header parsed", "re-probe")),
        CapabilityBinding("image.resize", "image", "resize", AdapterKind.NATIVE,
            metadata = meta("image", "ย่อรูปด้านยาวสุด", listOf("src,maxDim?"), listOf("dst"), listOf("fs.write"), false, "dims fit", "retry")),
        CapabilityBinding("image.crop", "image", "crop", AdapterKind.NATIVE,
            metadata = meta("image", "ครอปรูปตามกรอบ", listOf("src,x,y,w,h"), listOf("dst"), listOf("fs.write"), false, "dims match", "fix rect")),
        CapabilityBinding("image.rotate", "image", "rotate", AdapterKind.NATIVE,
            metadata = meta("image", "หมุนรูป 90/180/270", listOf("src,degrees?"), listOf("dst"), listOf("fs.write"), false, "dims swapped", "retry")),
        CapabilityBinding("image.grayscale", "image", "grayscale", AdapterKind.NATIVE,
            metadata = meta("image", "ทำรูปขาวดำ", listOf("src"), listOf("dst"), listOf("fs.write"), false, "luma only", "retry")),
        CapabilityBinding("image.scopes", "image", "scopes", AdapterKind.NATIVE,
            metadata = meta("image", "ฮิสโตแกรม+วัดแสงรูป", listOf("path"), listOf("scopes"), emptyList(), false, "verdict shown", "fix file")),
        CapabilityBinding("image.adjust", "image", "adjust", AdapterKind.NATIVE,
            metadata = meta("image", "แต่งภาพ (แสง/คอนทราสต์/สี/คม)", listOf("src,brightness?,contrast?,saturation?,sharpness?"), listOf("dst"), listOf("fs.write"), false, "adjusted", "fix file")),
        CapabilityBinding("image.upscale", "image", "upscale", AdapterKind.NATIVE,
            metadata = meta("image", "ขยายภาพ 2x/4x bicubic", listOf("src,scale?"), listOf("dst"), listOf("fs.write"), false, "upscaled", "fix file")),
        CapabilityBinding("image.restore", "image", "restore", AdapterKind.NATIVE,
            metadata = meta("image", "ฟื้นฟูภาพเก่า", listOf("src"), listOf("dst"), listOf("fs.write"), false, "restored", "fix file")),
        // Audio engine (native, WAV pipeline + MediaCodec decode).
        CapabilityBinding("audio.info", "audio", "info", AdapterKind.NATIVE,
            metadata = meta("audio", "ดูฟอร์แมต+ความยาวเสียง", listOf("path"), listOf("info"), emptyList(), false, "header parsed", "re-probe")),
        CapabilityBinding("audio.trim", "audio", "trim", AdapterKind.NATIVE,
            metadata = meta("audio", "ตัดเสียงตามช่วงเวลา", listOf("src,startMs,endMs"), listOf("dst"), listOf("fs.write"), false, "duration match", "fix range")),
        CapabilityBinding("audio.concat", "audio", "concat", AdapterKind.NATIVE,
            metadata = meta("audio", "ต่อไฟล์เสียง", listOf("srcs"), listOf("dst"), listOf("fs.write"), false, "duration sum", "fix files")),
        CapabilityBinding("audio.gain", "audio", "gain", AdapterKind.NATIVE,
            metadata = meta("audio", "เร่ง/เบาเสียง", listOf("src,db"), listOf("dst"), listOf("fs.write"), false, "peak changed", "retry")),
        CapabilityBinding("audio.fade", "audio", "fade", AdapterKind.NATIVE,
            metadata = meta("audio", "เฟดหัว/ท้ายเสียง", listOf("src,inMs?,outMs?"), listOf("dst"), listOf("fs.write"), false, "ramps ok", "retry")),
        CapabilityBinding("audio.beats", "audio", "beats", AdapterKind.NATIVE,
            metadata = meta("audio", "จับจังหวะเพลง (BPM)", listOf("src"), listOf("bpm"), emptyList(), false, "bpm shown", "retry")),
        CapabilityBinding("audio.voicefx", "audio", "voicefx", AdapterKind.NATIVE,
            metadata = meta("audio", "เปลี่ยนเสียงพูด", listOf("src,semitones?,robot?,echoMs?,echoDecay?"), listOf("dst"), listOf("fs.write"), false, "fx ok", "retry")),
        CapabilityBinding("audio.synthmusic", "audio", "synthmusic", AdapterKind.NATIVE,
            metadata = meta("audio", "ทำดนตรีประกอบ", listOf("style?,seconds?,dst?"), listOf("dst"), listOf("fs.write"), false, "music ok", "retry")),
        CapabilityBinding("audio.synthsfx", "audio", "synthsfx", AdapterKind.NATIVE,
            metadata = meta("audio", "ทำเสียงเอฟเฟกต์", listOf("kind,dst?"), listOf("dst"), listOf("fs.write"), false, "sfx ok", "retry")),
        CapabilityBinding("audio.speech", "audio", "speech", AdapterKind.NATIVE,
            metadata = meta("audio", "หาช่วงเสียงพูด", listOf("src,thresholdDb?"), listOf("ranges"), emptyList(), false, "ranges shown", "retry")),
        CapabilityBinding("audio.recordStart", "audio", "recordStart", AdapterKind.NATIVE,
            metadata = meta("audio", "เริ่มอัดเสียง", listOf("dst"), listOf("ok"), listOf("mic"), false, "recording", "grant mic")),
        CapabilityBinding("audio.recordStop", "audio", "recordStop", AdapterKind.NATIVE,
            metadata = meta("audio", "หยุดอัดเสียง", emptyList(), listOf("dst"), listOf("mic"), false, "file saved", "retry")),
        CapabilityBinding("audio.mix", "audio", "mix", AdapterKind.NATIVE,
            metadata = meta("audio", "ผสมเสียง 2 ไฟล์", listOf("srcA,srcB,gainB?,offsetMs?"), listOf("dst"), listOf("fs.write"), false, "mixed", "fix file")),
        CapabilityBinding("audio.normalize", "audio", "normalize", AdapterKind.NATIVE,
            metadata = meta("audio", "นอร์มัลไลซ์เสียง", listOf("src,peakDb?"), listOf("dst"), listOf("fs.write"), false, "normalized", "fix file")),
        CapabilityBinding("audio.autocut", "audio", "autocut", AdapterKind.NATIVE,
            metadata = meta("audio", "ตัดเงียบไฟล์เสียง", listOf("src"), listOf("dst"), listOf("fs.write"), false, "cut", "fix file")),
        CapabilityBinding("audio.podcast", "audio", "podcast", AdapterKind.NATIVE,
            metadata = meta("audio", "ทำพอดแคสต์ (ตัดเงียบ+นอร์มัล+ดนตรี)", listOf("voice,bed?,dst?"), listOf("dst"), listOf("fs.write"), false, "podcast ready", "fix file")),
        // Video engine (native, MP4 probe + stream-copy ops).
        CapabilityBinding("video.info", "video", "info", AdapterKind.NATIVE,
            metadata = meta("video", "ดูฟอร์แมต+ขนาด+ความยาววิดีโอ", listOf("path"), listOf("info"), emptyList(), false, "header parsed", "re-probe")),
        CapabilityBinding("video.thumbnail", "video", "thumbnail", AdapterKind.NATIVE,
            metadata = meta("video", "จับภาพปกจากวิดีโอ", listOf("src,timeMs?"), listOf("dst"), listOf("fs.write"), false, "png written", "retry")),
        CapabilityBinding("video.trim", "video", "trim", AdapterKind.NATIVE,
            metadata = meta("video", "ตัดวิดีโอตามช่วงเวลา (ไม่ re-encode)", listOf("src,startMs,endMs"), listOf("dst"), listOf("fs.write"), false, "duration match", "fix range")),
        CapabilityBinding("video.extractAudio", "video", "extractAudio", AdapterKind.NATIVE,
            metadata = meta("video", "ดึงแทร็กเสียงจากวิดีโอ", listOf("src"), listOf("dst"), listOf("fs.write"), false, "audio track out", "retry")),
        CapabilityBinding("video.proxy", "video", "proxy", AdapterKind.NATIVE,
            metadata = meta("video", "ทำไฟล์พร็อกซีตัดต่อ", listOf("src,maxDim?,dst?"), listOf("dst"), listOf("fs.write"), false, "proxy ready", "fix file")),
        CapabilityBinding("video.multicam.sync", "video", "multicam.sync", AdapterKind.NATIVE,
            metadata = meta("video", "ซิงก์มัลติแคม", listOf("paths", "method?"), listOf("group"), listOf("fs.read"), false, "synced", "retry")),
        CapabilityBinding("video.multicam.cut", "video", "multicam.cut", AdapterKind.NATIVE,
            metadata = meta("video", "ตัดมุมมัลติแคม", listOf("group", "atMs", "angle"), listOf("group"), emptyList(), false, "cut added", "retry")),
        CapabilityBinding("video.multicam.edl", "video", "multicam.edl", AdapterKind.NATIVE,
            metadata = meta("video", "ออกรายการตัดมัลติแคม", listOf("group"), listOf("edl"), emptyList(), false, "edl ready", "retry")),
        CapabilityBinding("video.scopes", "video", "scopes", AdapterKind.NATIVE,
            metadata = meta("video", "ดูสโคปวิดีโอ", listOf("path", "atMs?"), listOf("scopes"), listOf("fs.read"), false, "scopes shown", "retry")),
        // Media projects (native, file stores).
        CapabilityBinding("media.project.create", "media", "project.create", AdapterKind.NATIVE,
            metadata = meta("media", "สร้างโปรเจกต์ใหม่", listOf("name?"), listOf("project"), emptyList(), false, "id listed", "retry", true, "edit.undo")),
        CapabilityBinding("media.project.list", "media", "project.list", AdapterKind.NATIVE,
            metadata = meta("media", "list โปรเจกต์", emptyList(), listOf("projects"), emptyList(), false, "dir read", "re-list")),
        CapabilityBinding("media.asset.import", "media", "asset.import", AdapterKind.NATIVE,
            metadata = meta("media", "import ไฟล์เข้าโปรเจกต์", listOf("path,projectId?"), listOf("asset"), listOf("fs.write"), false, "asset listed", "fix file", true, "edit.undo")),
        CapabilityBinding("media.asset.list", "media", "asset.list", AdapterKind.NATIVE,
            metadata = meta("media", "list asset ในโปรเจกต์", listOf("projectId?"), listOf("assets"), emptyList(), false, "index read", "re-list")),
        CapabilityBinding("media.timeline.get", "media", "timeline.get", AdapterKind.NATIVE,
            metadata = meta("media", "อ่าน timeline", listOf("projectId?"), listOf("timeline"), emptyList(), false, "json read", "re-get")),
        CapabilityBinding("media.timeline.addClip", "media", "timeline.addClip", AdapterKind.NATIVE,
            metadata = meta("media", "วางคลิปบน timeline", listOf("assetId,startMs,endMs,atMs"), listOf("ok"), listOf("fs.write"), false, "clip listed", "fix args", true, "edit.undo")),
        CapabilityBinding("media.version.save", "media", "version.save", AdapterKind.NATIVE,
            metadata = meta("media", "บันทึกเวอร์ชัน timeline", listOf("projectId?"), listOf("version"), listOf("fs.write"), false, "snap written", "retry", true, "edit.undo")),
        CapabilityBinding("media.version.list", "media", "version.list", AdapterKind.NATIVE,
            metadata = meta("media", "list เวอร์ชัน", listOf("projectId?"), listOf("versions"), emptyList(), false, "dir read", "re-list")),
        CapabilityBinding("media.version.restore", "media", "version.restore", AdapterKind.NATIVE,
            metadata = meta("media", "ย้อน timeline ไปเวอร์ชัน", listOf("version,projectId?"), listOf("ok"), listOf("fs.write"), false, "timeline match", "re-restore", true, "edit.undo")),
        CapabilityBinding("media.project.rename", "media", "project.rename", AdapterKind.NATIVE,
            metadata = meta("media", "เปลี่ยนชื่อโปรเจกต์", listOf("name,projectId?"), listOf("project"), listOf("fs.write"), false, "name match", "retry", true, "edit.undo")),
        CapabilityBinding("media.project.duplicate", "media", "project.duplicate", AdapterKind.NATIVE,
            metadata = meta("media", "สำเนาโปรเจกต์", listOf("projectId?"), listOf("project"), listOf("fs.write"), false, "copy listed", "retry", true, "edit.undo")),
        CapabilityBinding("media.project.delete", "media", "project.delete", AdapterKind.NATIVE,
            metadata = meta("media", "ลบโปรเจกต์ (เข้าถังขยะ)", listOf("projectId?"), listOf("trashId"), listOf("fs.write"), false, "trash listed", "project.restore", true, "edit.undo")),
        CapabilityBinding("media.project.trash", "media", "project.trash", AdapterKind.NATIVE,
            metadata = meta("media", "list ถังขยะโปรเจกต์", emptyList(), listOf("trashIds"), emptyList(), false, "dir read", "re-list")),
        CapabilityBinding("media.project.restore", "media", "project.restore", AdapterKind.NATIVE,
            metadata = meta("media", "กู้โปรเจกต์จากถังขยะ", listOf("trashId"), listOf("project"), listOf("fs.write"), false, "id listed", "check id", true, "edit.undo")),
        CapabilityBinding("media.project.backup", "media", "project.backup", AdapterKind.NATIVE,
            metadata = meta("media", "แบ็คอัพโปรเจกต์", listOf("projectId?"), listOf("backupId"), listOf("fs.write"), false, "dir copied", "retry")),
        CapabilityBinding("media.edit.undo", "media", "edit.undo", AdapterKind.NATIVE,
            metadata = meta("media", "เลิกทำ", listOf("projectId?"), listOf("label"), emptyList(), false, "state match", "edit.redo")),
        CapabilityBinding("media.edit.redo", "media", "edit.redo", AdapterKind.NATIVE,
            metadata = meta("media", "ทำซ้ำ", listOf("projectId?"), listOf("label"), emptyList(), false, "state match", "edit.undo")),
        CapabilityBinding("media.edit.history", "media", "edit.history", AdapterKind.NATIVE,
            metadata = meta("media", "ประวัติเลิกทำ + เหตุการณ์", listOf("projectId?"), listOf("history"), emptyList(), false, "log read", "re-get")),
        CapabilityBinding("media.checkpoint.save", "media", "checkpoint.save", AdapterKind.NATIVE,
            metadata = meta("media", "บันทึกเช็คพอยต์", listOf("reason?,projectId?"), listOf("id"), listOf("fs.write"), false, "file written", "retry")),
        CapabilityBinding("media.checkpoint.list", "media", "checkpoint.list", AdapterKind.NATIVE,
            metadata = meta("media", "list เช็คพอยต์", listOf("projectId?"), listOf("ids"), emptyList(), false, "dir read", "re-list")),
        CapabilityBinding("media.checkpoint.recover", "media", "checkpoint.recover", AdapterKind.NATIVE,
            metadata = meta("media", "กู้เช็คพอยต์", listOf("id?,projectId?"), listOf("project"), listOf("fs.write"), false, "state match", "check id", true, "edit.undo")),
        CapabilityBinding("media.timeline.splitClip", "media", "timeline.splitClip", AdapterKind.NATIVE,
            metadata = meta("media", "แยกคลิป", listOf("clipIndex,atMs"), listOf("ok"), listOf("fs.write"), false, "2 clips", "fix time", true, "edit.undo")),
        CapabilityBinding("media.timeline.trimClip", "media", "timeline.trimClip", AdapterKind.NATIVE,
            metadata = meta("media", "ทริมคลิป", listOf("clipIndex,startMs?,endMs?,atMs?"), listOf("ok"), listOf("fs.write"), false, "edges set", "fix args", true, "edit.undo")),
        CapabilityBinding("media.timeline.moveClip", "media", "timeline.moveClip", AdapterKind.NATIVE,
            metadata = meta("media", "ย้ายคลิป", listOf("clipIndex,toAtMs,toTrack?"), listOf("ok"), listOf("fs.write"), false, "pos match", "fix args", true, "edit.undo")),
        CapabilityBinding("media.timeline.deleteClip", "media", "timeline.deleteClip", AdapterKind.NATIVE,
            metadata = meta("media", "ลบคลิป", listOf("clipIndex"), listOf("ok"), listOf("fs.write"), false, "clip gone", "fix index", true, "edit.undo")),
        CapabilityBinding("media.timeline.duplicateClip", "media", "timeline.duplicateClip", AdapterKind.NATIVE,
            metadata = meta("media", "สำเนาคลิป", listOf("clipIndex,atMs?"), listOf("ok"), listOf("fs.write"), false, "2 clips", "fix index", true, "edit.undo")),
        CapabilityBinding("media.timeline.addMarker", "media", "timeline.addMarker", AdapterKind.NATIVE,
            metadata = meta("media", "เพิ่มมาร์กเกอร์", listOf("atMs,label?"), listOf("marker"), listOf("fs.write"), false, "marker listed", "fix time", true, "edit.undo")),
        CapabilityBinding("media.timeline.removeMarker", "media", "timeline.removeMarker", AdapterKind.NATIVE,
            metadata = meta("media", "ลบมาร์กเกอร์", listOf("markerId"), listOf("ok"), listOf("fs.write"), false, "marker gone", "check id", true, "edit.undo")),
        CapabilityBinding("media.timeline.trackFlags", "media", "timeline.trackFlags", AdapterKind.NATIVE,
            metadata = meta("media", "ตั้งค่าแทร็ก", listOf("trackId,locked?,muted?,hidden?"), listOf("track"), listOf("fs.write"), false, "flags match", "check id", true, "edit.undo")),
        CapabilityBinding("media.timeline.transformClip", "media", "timeline.transformClip", AdapterKind.NATIVE,
            metadata = meta("media", "ครอป/หมุน/พลิก/ซูม/ย้าย/โปร่งใสคลิป", listOf("clipIndex,rotation?,flipH?,flipV?,crop?,scale?,pos?,opacity?"), listOf("ok"), listOf("fs.write"), false, "transform shown", "fix args", true, "edit.undo")),
        CapabilityBinding("media.timeline.freezeFrame", "media", "timeline.freezeFrame", AdapterKind.NATIVE,
            metadata = meta("media", "ฟรีซเฟรม", listOf("clipIndex,frameMs?,holdMs?"), listOf("ok"), listOf("fs.write"), false, "still inserted", "video only", true, "edit.undo")),
        CapabilityBinding("media.timeline.addText", "media", "timeline.addText", AdapterKind.NATIVE,
            metadata = meta("media", "เพิ่มข้อความ", listOf("text,startMs?,endMs?,preset?"), listOf("ok"), listOf("fs.write"), false, "text listed", "fix time", true, "edit.undo")),
        CapabilityBinding("media.timeline.updateText", "media", "timeline.updateText", AdapterKind.NATIVE,
            metadata = meta("media", "แก้ข้อความ", listOf("textIndex,..."), listOf("ok"), listOf("fs.write"), false, "text shown", "check id", true, "edit.undo")),
        CapabilityBinding("media.timeline.removeText", "media", "timeline.removeText", AdapterKind.NATIVE,
            metadata = meta("media", "ลบข้อความ", listOf("textIndex"), listOf("ok"), listOf("fs.write"), false, "text gone", "check id", true, "edit.undo")),
        CapabilityBinding("media.timeline.setSpeed", "media", "timeline.setSpeed", AdapterKind.NATIVE,
            metadata = meta("media", "ความเร็ว/ย้อนกลับ/ramp คลิป", listOf("clipIndex,rate?,reverse?,curve?"), listOf("ok"), listOf("fs.write"), false, "speed shown", "25..400", true, "edit.undo")),
        CapabilityBinding("media.timeline.setKeyframe", "media", "timeline.setKeyframe", AdapterKind.NATIVE,
            metadata = meta("media", "ตั้งคีย์เฟรมคลิป", listOf("clipIndex,prop,atMs,value,ease?"), listOf("ok"), listOf("fs.write"), false, "key shown", "fix prop", true, "edit.undo")),
        CapabilityBinding("media.timeline.removeKeyframe", "media", "timeline.removeKeyframe", AdapterKind.NATIVE,
            metadata = meta("media", "ลบคีย์เฟรมคลิป", listOf("clipIndex,prop,atMs"), listOf("ok"), listOf("fs.write"), false, "key gone", "check id", true, "edit.undo")),
        CapabilityBinding("media.timeline.clearKeyframes", "media", "timeline.clearKeyframes", AdapterKind.NATIVE,
            metadata = meta("media", "ล้างคีย์เฟรมคลิป", listOf("clipIndex,prop?"), listOf("ok"), listOf("fs.write"), false, "keys gone", "check id", true, "edit.undo")),
        CapabilityBinding("media.timeline.setTransition", "media", "timeline.setTransition", AdapterKind.NATIVE,
            metadata = meta("media", "ตั้งทรานซิชันคลิป", listOf("clipIndex,edge?,kind?,durationMs?"), listOf("ok"), listOf("fs.write"), false, "trans shown", "fix kind", true, "edit.undo")),
        CapabilityBinding("media.timeline.clearTransition", "media", "timeline.clearTransition", AdapterKind.NATIVE,
            metadata = meta("media", "ล้างทรานซิชันคลิป", listOf("clipIndex,edge?"), listOf("ok"), listOf("fs.write"), false, "trans gone", "check id", true, "edit.undo")),
        CapabilityBinding("media.timeline.setFx", "media", "timeline.setFx", AdapterKind.NATIVE,
            metadata = meta("media", "เอฟเฟกต์ภาพคลิป", listOf("clipIndex,blur?,vignette?,grain?"), listOf("ok"), listOf("fs.write"), false, "fx shown", "0..10/100", true, "edit.undo")),
        CapabilityBinding("media.timeline.setColor", "media", "timeline.setColor", AdapterKind.NATIVE,
            metadata = meta("media", "แก้สีคลิป", listOf("clipIndex,preset?,brightness?,contrast?,saturation?,temperature?,tint?,highlights?,shadows?,hueShift?,lightness?,exposure?,whites?,blacks?"), listOf("ok"), listOf("fs.write"), false, "color shown", "fix range", true, "edit.undo")),
        CapabilityBinding("media.timeline.setMask", "media", "timeline.setMask", AdapterKind.NATIVE,
            metadata = meta("media", "มาสก์คลิป", listOf("clipIndex,shape?,x?,y?,w?,h?,feather?,invert?"), listOf("ok"), listOf("fs.write"), false, "mask shown", "fix rect", true, "edit.undo")),
        CapabilityBinding("media.timeline.setChroma", "media", "timeline.setChroma", AdapterKind.NATIVE,
            metadata = meta("media", "chroma คลิป", listOf("clipIndex,hue?,tolerance?,softness?,despill?,off?"), listOf("ok"), listOf("fs.write"), false, "chroma shown", "0..360", true, "edit.undo")),
        CapabilityBinding("media.timeline.setBackground", "media", "timeline.setBackground", AdapterKind.NATIVE,
            metadata = meta("media", "พื้นหลังไทม์ไลน์", listOf("mode,color?,blur?,assetId?"), listOf("ok"), listOf("fs.write"), false, "bg shown", "fix mode", true, "edit.undo")),
        CapabilityBinding("media.timeline.track", "media", "timeline.track", AdapterKind.NATIVE,
            metadata = meta("media", "แทร็กวัตถุในคลิป", listOf("clipIndex,x?,y?,w?,h?,startMs?,endMs?,stepMs?,target?"), listOf("ok"), listOf("fs.write"), false, "path applied", "fix rect", true, "edit.undo")),
        CapabilityBinding("media.timeline.stabilize", "media", "timeline.stabilize", AdapterKind.NATIVE,
            metadata = meta("media", "กันสั่นคลิป", listOf("clipIndex,startMs?,endMs?,stepMs?,smoothMs?,zoom?"), listOf("ok"), listOf("fs.write"), false, "stab applied", "fix range", true, "edit.undo")),
        CapabilityBinding("media.timeline.lut", "media", "timeline.lut", AdapterKind.NATIVE,
            metadata = meta("media", "ใส่ LUT (.cube) ให้คลิป", listOf("clipIndex,path,strength?"), listOf("ok"), listOf("fs.write"), false, "lut shown", "fix .cube", true, "edit.undo")),
        CapabilityBinding("media.timeline.lutClear", "media", "timeline.lutClear", AdapterKind.NATIVE,
            metadata = meta("media", "ล้าง LUT คลิป", listOf("clipIndex"), listOf("ok"), listOf("fs.write"), false, "lut cleared", "fix clip", true, "edit.undo")),
        CapabilityBinding("media.timeline.setColor", "media", "timeline.setColor", AdapterKind.NATIVE,
            metadata = meta("media", "แก้สีคลิป (ทุกช่อง+วงล้อ)", listOf("clipIndex"), listOf("ok"), listOf("fs.write"), false, "color set", "fix args", true, "edit.undo")),
        CapabilityBinding("media.timeline.colorAuto", "media", "timeline.colorAuto", AdapterKind.NATIVE,
            metadata = meta("media", "ปรับสีอัตโนมัติ (วัดจากเฟรมจริง)", listOf("clipIndex"), listOf("ok"), listOf("fs.write"), false, "auto applied", "fix clip", true, "edit.undo")),
        CapabilityBinding("media.template.save", "media", "template.save", AdapterKind.NATIVE,
            metadata = meta("media", "บันทึกเทมเพลตจากโปรเจกต์", listOf("name,category?,slots?,description?"), listOf("ok"), listOf("fs.write"), false, "template saved", "fix slots", true, "edit.undo")),
        CapabilityBinding("media.template.list", "media", "template.list", AdapterKind.NATIVE,
            metadata = meta("media", "list เทมเพลต", listOf("category?"), listOf("templates"), emptyList(), false, "templates listed", "fix category")),
        CapabilityBinding("media.template.apply", "media", "template.apply", AdapterKind.NATIVE,
            metadata = meta("media", "ใช้เทมเพลตกับโปรเจกต์", listOf("templateId,replacements?"), listOf("ok"), listOf("fs.write"), false, "template applied", "fix slots", true, "edit.undo")),
        CapabilityBinding("media.template.delete", "media", "template.delete", AdapterKind.NATIVE,
            metadata = meta("media", "ลบเทมเพลต", listOf("templateId"), listOf("ok"), listOf("fs.write"), false, "template deleted", "fix id", true, "edit.undo")),
        CapabilityBinding("media.library.add", "media", "library.add", AdapterKind.NATIVE,
            metadata = meta("media", "เพิ่ม asset เข้าคลัง", listOf("kind,name,tags?,ref?"), listOf("ok"), listOf("fs.write"), false, "added", "fix kind", true, "edit.undo")),
        CapabilityBinding("media.library.list", "media", "library.list", AdapterKind.NATIVE,
            metadata = meta("media", "list คลัง asset", listOf("kind?"), listOf("items"), emptyList(), false, "items listed", "fix kind")),
        CapabilityBinding("media.library.search", "media", "library.search", AdapterKind.NATIVE,
            metadata = meta("media", "ค้นหาคลัง asset", listOf("query"), listOf("items"), emptyList(), false, "results shown", "fix query")),
        CapabilityBinding("media.library.remove", "media", "library.remove", AdapterKind.NATIVE,
            metadata = meta("media", "ลบ asset ออกจากคลัง", listOf("itemId"), listOf("ok"), listOf("fs.write"), false, "removed", "fix id", true, "edit.undo")),
        CapabilityBinding("media.gen.list", "media", "gen.list", AdapterKind.NATIVE,
            metadata = meta("media", "list ตัวสร้างมีเดีย", emptyList(), listOf("providers"), emptyList(), false, "providers listed", "—")),
        CapabilityBinding("media.gen.make", "media", "gen.make", AdapterKind.NATIVE,
            metadata = meta("media", "สร้างมีเดีย (โปสเตอร์/พื้นหลัง/แต่งรูป/เสียงพูด)", listOf("kind,prompt?,path?,style?,w?,h?,lang?"), listOf("assetId"), listOf("fs.write"), false, "asset imported", "fix kind", true, "edit.undo")),
        CapabilityBinding("media.timeline.motion", "media", "timeline.motion", AdapterKind.NATIVE,
            metadata = meta("media", "โมชัน Ken Burns ของคลิป", listOf("clipIndex,dir?,zoom?,off?"), listOf("ok"), listOf("fs.write"), false, "motion shown", "fix dir", true, "edit.undo")),
        CapabilityBinding("media.timeline.slideshow", "media", "timeline.slideshow", AdapterKind.NATIVE,
            metadata = meta("media", "ทำสไลด์โชว์จากรูป", listOf("assetIds,stillMs?,fadeMs?"), listOf("ok"), listOf("fs.write"), false, "slideshow added", "fix assets", true, "edit.undo")),
        CapabilityBinding("media.timeline.volume", "media", "timeline.volume", AdapterKind.NATIVE,
            metadata = meta("media", "ตั้งเสียงคลิป", listOf("clipIndex,volume"), listOf("ok"), listOf("fs.write"), false, "volume shown", "0..100", true, "edit.undo")),
        CapabilityBinding("media.timeline.beatsToMarkers", "media", "timeline.beatsToMarkers", AdapterKind.NATIVE,
            metadata = meta("media", "จับจังหวะคลิปเป็นมาร์กเกอร์", listOf("clipIndex"), listOf("ok"), listOf("fs.write"), false, "markers added", "fix audio", true, "edit.undo")),
        CapabilityBinding("media.timeline.autocut", "media", "timeline.autocut", AdapterKind.NATIVE,
            metadata = meta("media", "ตัดช่วงเงียบอัตโนมัติ", listOf("clipIndex,thresholdDb?,minSpeechMs?,minSilenceMs?"), listOf("ok"), listOf("fs.write"), false, "ranges kept", "fix audio", true, "edit.undo")),
        CapabilityBinding("media.timeline.highlights", "media", "timeline.highlights", AdapterKind.NATIVE,
            metadata = meta("media", "หาช็อตเด่นเป็นมาร์กเกอร์", listOf("clipIndex,count?,windowSec?"), listOf("ok"), listOf("fs.write"), false, "markers added", "fix audio", true, "edit.undo")),
        CapabilityBinding("media.timeline.reframe", "media", "timeline.reframe", AdapterKind.NATIVE,
            metadata = meta("media", "รีเฟรมคลิปตามสัดส่วน", listOf("clipIndex,aspect,subjectX?,subjectY?,punch?"), listOf("ok"), listOf("fs.write"), false, "reframed", "fix args", true, "edit.undo")),
        CapabilityBinding("media.timeline.setCanvas", "media", "timeline.setCanvas", AdapterKind.NATIVE,
            metadata = meta("media", "ตั้งสัดส่วนแคนวาส", listOf("aspect?"), listOf("ok"), listOf("fs.write"), false, "canvas set", "fix args", true, "edit.undo")),
        CapabilityBinding("media.timeline.colorMatch", "media", "timeline.colorMatch", AdapterKind.NATIVE,
            metadata = meta("media", "จับคู่สีตามคลิปอ้างอิง", listOf("clipIndex,refIndex"), listOf("ok"), listOf("fs.write"), false, "matched", "fix file", true, "edit.undo")),
        CapabilityBinding("media.text.aiplan", "media", "text.aiplan", AdapterKind.NATIVE,
            metadata = meta("media", "วางแผนคอนเทนต์ 5 โหมด AI", listOf("mode,topic,platform?"), listOf("plan"), emptyList(), false, "plan shown", "fix args")),
        CapabilityBinding("media.script.video", "media", "script.video", AdapterKind.NATIVE,
            metadata = meta("media", "สร้างวิดีโอจากบท", listOf("script,style?,lang?"), listOf("ok"), listOf("fs.write"), false, "video built", "fix script", true, "edit.undo")),
        CapabilityBinding("media.brand.save", "media", "brand.save", AdapterKind.NATIVE,
            metadata = meta("media", "บันทึกชุดแบรนด์", listOf("name,color?,logo?,tagline?"), listOf("id"), listOf("fs.write"), false, "brand saved", "fix args")),
        CapabilityBinding("media.brand.list", "media", "brand.list", AdapterKind.NATIVE,
            metadata = meta("media", "รายชื่อแบรนด์", emptyList(), listOf("brands"), emptyList(), false, "listed", "retry")),
        CapabilityBinding("media.brand.apply", "media", "brand.apply", AdapterKind.NATIVE,
            metadata = meta("media", "ใช้แบรนด์กับโปรเจกต์", listOf("brandId"), listOf("ok"), listOf("fs.write"), false, "branded", "fix id", true, "edit.undo")),
        CapabilityBinding("media.package", "media", "package", AdapterKind.NATIVE,
            metadata = meta("media", "แพ็กโปรเจกต์เป็น zip", listOf("projectId?,dst?"), listOf("zip"), listOf("fs.write"), false, "packaged", "fix path")),
        CapabilityBinding("render.batch", "render", "batch", AdapterKind.NATIVE,
            metadata = meta("render", "เรนเดอร์หลายโปรเจกต์", listOf("projectIds?/all?"), listOf("jobs"), listOf("fs.write"), false, "batch done", "fix ids")),
        CapabilityBinding("render.cache.status", "render", "cache.status", AdapterKind.NATIVE,
            metadata = meta("render", "ดูพื้นที่แคช", emptyList(), listOf("usage"), emptyList(), false, "usage shown", "retry")),
        CapabilityBinding("render.cache.clear", "render", "cache.clear", AdapterKind.NATIVE,
            metadata = meta("render", "ล้างแคช", listOf("days?"), listOf("freed"), listOf("fs.write"), false, "cache cleared", "retry")),
        CapabilityBinding("render.hwinfo", "render", "hwinfo", AdapterKind.NATIVE,
            metadata = meta("render", "ดูตัวเร่งฮาร์ดแวร์", emptyList(), listOf("codecs"), emptyList(), false, "codecs shown", "retry")),
CapabilityBinding("media.timeline.enhance", "media", "timeline.enhance", AdapterKind.NATIVE,
            metadata = meta("media", "ปรับปรุงคลิปอัตโนมัติ", listOf("clipIndex,strength?"), listOf("ok"), listOf("fs.write"), false, "enhanced", "fix file", true, "edit.undo")),
        CapabilityBinding("media.text.ideas", "media", "text.ideas", AdapterKind.NATIVE,
            metadata = meta("media", "ไอเดียข้อความ (hook/แคปชัน/CTA)", listOf("kind,topic,platform?"), listOf("ideas"), emptyList(), false, "ideas listed", "fix kind")),
        // Subtitle engine (native, SRT + burn-in).
        CapabilityBinding("subtitle.make", "subtitle", "make", AdapterKind.NATIVE,
            metadata = meta("subtitle", "ทำไฟล์ซับจากข้อความ", listOf("transcript,mediaPath?,durationMs?"), listOf("srt"), listOf("fs.write"), false, "cues > 0", "fix text")),
        CapabilityBinding("subtitle.parse", "subtitle", "parse", AdapterKind.NATIVE,
            metadata = meta("subtitle", "ตรวจไฟล์ซับ", listOf("path"), listOf("info"), emptyList(), false, "parse ok", "fix file")),
        CapabilityBinding("subtitle.shift", "subtitle", "shift", AdapterKind.NATIVE,
            metadata = meta("subtitle", "เลื่อนเวลาซับ", listOf("src,offsetMs"), listOf("dst"), listOf("fs.write"), false, "times moved", "retry")),
        CapabilityBinding("subtitle.burn", "subtitle", "burn", AdapterKind.NATIVE,
            metadata = meta("subtitle", "ฝังซับลงวิดีโอ", listOf("src,srt"), listOf("dst"), listOf("fs.write"), false, "mp4 out", "retry")),
        CapabilityBinding("subtitle.translate", "subtitle", "translate", AdapterKind.NATIVE,
            metadata = meta("subtitle", "แปลซับไทย↔อังกฤษ", listOf("src,direction?"), listOf("dst"), listOf("fs.write"), false, "translated", "fix file")),
        CapabilityBinding("render.enqueue", "render", "enqueue", AdapterKind.NATIVE,
            metadata = meta("render", "เข้าคิวเรนเดอร์", listOf("projectId?,preset?"), listOf("job"), emptyList(), false, "job queued", "retry")),
        CapabilityBinding("render.runNow", "render", "runNow", AdapterKind.NATIVE,
            metadata = meta("render", "เรนเดอร์ทันที", listOf("projectId?,preset?"), listOf("mp4"), listOf("fs.write"), false, "qc pass", "retry")),
        CapabilityBinding("render.run", "render", "run", AdapterKind.NATIVE,
            metadata = meta("render", "รันงานที่ค้าง", listOf("jobId"), listOf("mp4"), listOf("fs.write"), false, "qc pass", "retry")),
        CapabilityBinding("render.status", "render", "status", AdapterKind.NATIVE,
            metadata = meta("render", "สถานะงาน", listOf("jobId?"), listOf("info"), emptyList(), false, "job found", "check id")),
        CapabilityBinding("render.list", "render", "list", AdapterKind.NATIVE,
            metadata = meta("render", "รายการงาน", emptyList(), listOf("list"), emptyList(), false, "list ok", "retry")),
        CapabilityBinding("render.retry", "render", "retry", AdapterKind.NATIVE,
            metadata = meta("render", "ลองใหม่งานที่ล้มเหลว", listOf("jobId?"), listOf("job"), emptyList(), false, "requeued", "check id")),
        CapabilityBinding("render.approve", "render", "approve", AdapterKind.NATIVE,
            metadata = meta("render", "อนุมัติผลลัพธ์", listOf("jobId?"), listOf("job"), emptyList(), false, "qc passed", "fix timeline")),
        CapabilityBinding("render.export", "render", "export", AdapterKind.NATIVE,
            metadata = meta("render", "เอ็กซ์พอร์ตไป Download", listOf("jobId?"), listOf("uri"), listOf("fs.write"), false, "approved", "approve first")),
        // Compatibility engine — CLI adapter, LAST resort (§29, CP-32).
        CapabilityBinding("terminal.open", "terminal", "open", AdapterKind.CLI_ADAPTER,
            metadata = meta("terminal", "เปิด terminal session", emptyList(), listOf("sessionId"), listOf("terminal"), false, "session listed", "re-open")),
        CapabilityBinding("terminal.exec", "terminal", "exec", AdapterKind.CLI_ADAPTER,
            metadata = meta("terminal", "รันคำสั่งใน session", listOf("sessionId,command"), listOf("output"), listOf("terminal"), false, "exit code", "repair ladder")),
        CapabilityBinding("terminal.close", "terminal", "close", AdapterKind.CLI_ADAPTER,
            metadata = meta("terminal", "ปิด session", listOf("sessionId"), listOf("ok"), emptyList(), false, "session gone", "force close")),
        CapabilityBinding("terminal.sessions", "terminal", "sessions", AdapterKind.CLI_ADAPTER,
            metadata = meta("terminal", "list sessions", emptyList(), listOf("sessions"), emptyList(), false, "session count", "re-list")),
    )

    /** Resolver over a live registry (production: ServiceLocator's registry). */
    fun overRegistry(registry: ToolRegistry): CapabilityResolver =
        DefaultCapabilityResolver(registry).also { resolver ->
            bindings().forEach { resolver.register(it) }
        }

    /**
     * Standalone resolver for tests/embedders without the app registry.
     * Mirrors the tools this app build actually ships runnable.
     */
    fun defaultResolver(): CapabilityResolver {
        val registry = InMemoryToolRegistry()
        for (toolId in listOf("files", "editor", "git", "browser", "debug", "memory", "skill", "voice", "image", "audio", "video", "media", "subtitle", "render")) {
            registry.register(runnableDescriptor(toolId))
        }
        return overRegistry(registry)
    }

    private fun runnableDescriptor(toolId: String): ToolDescriptor = ToolDescriptor(
        toolId = toolId,
        displayName = toolId,
        version = "0.0.0-standalone",
        layers = listOf(
            LayerCapability(CapabilityLayer.RUNTIME, CapabilityStatus.AVAILABLE, "shipped in this build"),
            LayerCapability(CapabilityLayer.EXECUTION, CapabilityStatus.AVAILABLE, "via ToolGateway"),
        ),
    )
}

private fun meta(
    tool: String, purpose: String, inputs: List<String>, outputs: List<String>,
    permissions: List<String>, network: Boolean, verification: String, recovery: String,
    undoable: Boolean = false, undoHint: String = "",
): CapabilityMetadata {
    val engines = mapOf(
        "files" to ("File Engine" to "SandboxFileStore"),
        "editor" to ("Code Engine" to "FileBackedEditor"),
        "git" to ("Git Engine" to "JGit"),
        "browser" to ("Browser Engine" to "WebView + tab store"),
        "debug" to ("Debug Engine" to "StackTraceParser + DebugSession"),
        "memory" to ("Memory Engine" to "FileMemoryStore"),
        "skill" to ("Skill Engine" to "FileSkillStore"),
        "voice" to ("Voice Engine" to "SpeechRecognizer + TTS"),
        "image" to ("Image Engine" to "header probe + pixel ops"),
        "audio" to ("Audio Engine" to "WAV pipeline + MediaCodec"),
        "video" to ("Video Engine" to "MP4 probe + Muxer"),
        "media" to ("Media Engine" to "project stores"),
        "subtitle" to ("Subtitle Engine" to "SRT + transcode"),
        "render" to ("Render Engine" to "queue + QC + export"),
        "terminal" to ("Compatibility Engine" to "Termux bridge (pending device work)"),
    )
    val (engine, runtime) = engines.getValue(tool)
    return CapabilityMetadata(
        name = purpose, category = tool, purpose = purpose, engine = engine, runtime = runtime,
        operations = listOf(tool), inputs = inputs, outputs = outputs,
        dependencies = if (tool == "editor") listOf("files") else emptyList(),
        permissions = permissions, needsNetwork = network, needsStorage = tool != "browser",
        compatibility = if (tool == "terminal") "requires Termux bridge" else "native",
        fallback = "", verification = verification, recovery = recovery,
        undoable = undoable, undoHint = undoHint,
    )
}
